---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12
  commands:
  - go test -v -cover ./...
  - CGO_ENABLED=0 go build -o release/linux/amd64/drone-amazon-secrets github.com/drone/drone-amazon-secrets/cmd/drone-amazon-secrets

# - name: publish
#   image: plugins/docker
#   settings:
#     auto_tag: true
#     dockerfile: docker/Dockerfile
#     password:
#       from_secret: docker_password
#     repo: drone/amazon-secrets
#     username:
#       from_secret: docker_username

...